fail_fast: false
default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-xml
    -   id: detect-private-key
    -   id: name-tests-test
    -   id: check-added-large-files
-   repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
    # - id: black-jupyter
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: ["--max-line-length 100", "--ignore E501,E402"]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.2
    hooks:
      - id: nbqa-black
      - id: nbqa-flake8
      - id: nbqa-isort
-   repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
    - id: nbstripout
